package view;


import controller.Controller;
import exception.CVVException;
import exception.CardNumberException;
import exception.InvalidNumberMoviesException;
import exception.QueryModelException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 * Movie GUI represents the inital step to rent a movie that show a list of available movies to be rented. 
 * @author 
 */
public class Movie extends javax.swing.JFrame {
    
    private Controller controller; 
      
    /**
     * Creates a new Movie form centralized in the window.  
     */
    public Movie() {
        initComponents();  
        setLocationRelativeTo(null);
    }

    /**
     * Creates a new Movie form centralized in the window with a Controller object.
     * @param controller - the application controller object
     */
    Movie(Controller controller) {
        this();
        this.controller = controller; 
        initMoviesTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        moviesTable = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBasket = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jScrollPane1.setToolTipText("");
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setName(""); // NOI18N

        moviesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
            },
            new String [] {
                "MOVIE ID", "TITLE", "DESCRIPTION"
            }
        ));
        jScrollPane1.setViewportView(moviesTable);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Click a movie to Rent");

        btnAdd.setText("Add to the Basket");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBasket.setText("See the Basket");
        btnBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRefresh))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnBasket)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnBasket))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 0, 0));

        jMenu1.setText("Home");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    
    /***
     * Opens the initial screen and closes the Movie list screen
     * @param evt 
     */
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        new Welcome(controller).showFrame();
        this.dispose();
    }                                   
                                                                  

    /**
     * Adds a new Movie rental to the current customer basket. 
     * @param evt ActionEvent (press button)
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
        DefaultTableModel model = (DefaultTableModel) moviesTable.getModel();
        
        //gets the row information
        int row = moviesTable.getSelectedRow(); // get the select row
        String id = model.getValueAt(row, 0).toString();
        
        try {
            //add a new movie in the customer's basket. 
            controller.addMovie(Integer.valueOf(id), "", "", "");
        } catch (InvalidNumberMoviesException | QueryModelException | CardNumberException | CVVException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage(), "Invalid Number of Movies Renting", JOptionPane.ERROR_MESSAGE);
        }
        //updates the table visualization
        model.removeRow(row);
        model.fireTableDataChanged();
    }                                      

    /**
     * Shows the ShoppingBasket form with a list of movies select by the customer.
     * @param evt press button
     */
    private void btnBasketActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ShoppingBasket basket = new ShoppingBasket(controller);
        basket.show();
        this.dispose();
    }                                         

    /**
     * Refresh all available movies. 
     * @param evt press button
     */
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {                                           
        initMoviesTable();
    }                                          

  
    /**
     * Inits the movie table using all available movies data in the machine. 
     */
    private void initMoviesTable(){
        List<String[]> movies = controller.listMovies();
        DefaultTableModel tbModel = (DefaultTableModel) moviesTable.getModel(); 
        for(int i = tbModel.getRowCount() - 1; i >= 0; i--){
            tbModel.removeRow(i);
        }
        movies.forEach(tbModel::addRow);
        tbModel.fireTableDataChanged();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBasket;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable moviesTable;
    // End of variables declaration                   
}

