package view;


import controller.Controller;
import exception.QueryModelException;
import exception.UpdateModelException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * ReturnMovie GUI represent the returning movie process where the customer brings back the movie disc to the machine to return.
 * @author 
 */
public class ReturnMovie extends javax.swing.JFrame {

    private Controller controller; 
    /**
     * Creates new ReturnMovie form centralized in the window.  
     */
    public ReturnMovie() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Creates new ReturnMovie form centralized in the window with a Controller object.
     * @param controller - the application controller object.
     */
    ReturnMovie(Controller controller) {
        this();
        this.controller = controller; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMovieId = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnProceed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Return Movie");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Enter movie disc code");

        txtMovieId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieIdActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        btnProceed.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProceed.setText("PROCEED");
        btnProceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProceedMouseClicked(evt);
            }
        });
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txtMovieId, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnProceed)
                .addGap(37, 37, 37)
                .addComponent(btnCancel)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMovieId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnProceed))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMovieIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieIdActionPerformed

    /**
     * Cancels the retun processing and comes back to the initial screen.
     * @param evt 
     */
    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        this.dispose();
        new Welcome(controller).setVisible(true);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnProceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProceedMouseClicked
     
    }//GEN-LAST:event_btnProceedMouseClicked

    /**
     * Proceeds the returning process attending the business rules. 
     * @param evt press button
     */
    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        
        String movieId = txtMovieId.getText().trim().replace(" ", "");
        //checks if the movieId is not empty
        if(movieId.length() == 0){
             JOptionPane.showMessageDialog(null, "Please, enter with the Movie disc code", "Code number is empty", JOptionPane.WARNING_MESSAGE);
        } else {
            int id = Integer.valueOf(movieId);
            String [] info;
            try {
                //returning movie (if throws any exception theirs will be catched)
                info = this.controller.returnMovie(id);
                String message = info[0] + "\n" + info[1] + "\n" + info[2];
                JOptionPane.showMessageDialog(null,  message, "Return Movie disc was sucessful", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException | QueryModelException | UpdateModelException ex) {
                
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Return Movie ERROR", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }//GEN-LAST:event_btnProceedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnProceed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMovieId;
    // End of variables declaration//GEN-END:variables
}
