/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * ShoppingBasket GUI represents the proposal movies that will be rented. 
 * @author carlos
 */
public class ShoppingBasket extends javax.swing.JFrame {

    private final Controller controller; 
    
    /**
     * Creates a new ShoppingBasket form centralized in the window with a Controller object.
     * @param controller - the application controller object.
     */
    public ShoppingBasket(Controller controller) {
        this.controller = controller;
        initComponents();
        setLocationRelativeTo(null);
        initSelectedMoviesList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        moviesScroll = new javax.swing.JScrollPane();
        moviesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSeeMovies = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnRemoveMovie = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        moviesScroll.setToolTipText("");
        moviesScroll.setAutoscrolls(true);
        moviesScroll.setName(""); // NOI18N

        moviesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
            },
            new String [] {
                "MOVIE ID", "TITLE", "DESCRIPTION"
            }
        ));
        moviesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moviesTableMouseClicked(evt);
            }
        });
        moviesScroll.setViewportView(moviesTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Shopping Basket List");

        btnSeeMovies.setText("See More Movies");
        btnSeeMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeMoviesActionPerformed(evt);
            }
        });

        btnCheckout.setText("Check out");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnRemoveMovie.setText("Remove Movie");
        btnRemoveMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveMovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(moviesScroll)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSeeMovies)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveMovie)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(moviesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeeMovies)
                    .addComponent(btnCheckout)
                    .addComponent(btnRemoveMovie))
                .addContainerGap())
        );

        menuBar.setBackground(new java.awt.Color(255, 0, 0));

        jMenu1.setText("Home");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Closes this window and opens the initial screen. 
     * @param evt 
     */
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        new Welcome(controller).showFrame();
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void moviesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviesTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moviesTableMouseClicked

    /***
     * Opens the CheckOut screen and closes this window.
     * @param evt press button
     */
    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
        CheckOut checkout = new CheckOut(controller);
        checkout.show();
        this.dispose();
    }//GEN-LAST:event_btnCheckoutActionPerformed

    /***
     * Removes a movie from the basket movies list and updates the the basket list visualization. 
     * @param evt press button
     */
    private void btnRemoveMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveMovieActionPerformed
        // TODO add your handling code here:
        if(moviesTable.getRowCount() > 0){
            
            DefaultTableModel model = (DefaultTableModel) moviesTable.getModel();

            //gets the row movie id and removes it from basket list
            int row = moviesTable.getSelectedRow(); 
            String id = model.getValueAt(row, 0).toString();
            controller.removeMovie(Integer.valueOf(id));

            model.removeRow(row);
            model.fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, you don't have any movies to be removed. Please, see more movies to select one to your basket.", "Basket is empty", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveMovieActionPerformed

    /**
     * Closes this window and opens the Movie GUI list. 
     * @param evt press button
     */
    private void btnSeeMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeMoviesActionPerformed
        // TODO add your handling code here:
        Movie movie = new Movie(controller);
        movie.show();
        this.dispose();
    }//GEN-LAST:event_btnSeeMoviesActionPerformed

  
    /***
     * Inits the movie table with all movies in the customer's basket. 
     */
    private void initSelectedMoviesList(){
        List<String[]> movies = controller.listCustomerMovies();
        DefaultTableModel tbModel = (DefaultTableModel) moviesTable.getModel(); 
        for(int i = tbModel.getRowCount() - 1; i >= 0; i--){
            tbModel.removeRow(i);
        }
        movies.forEach(tbModel::addRow);
        tbModel.fireTableDataChanged();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnRemoveMovie;
    private javax.swing.JButton btnSeeMovies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JScrollPane moviesScroll;
    private javax.swing.JTable moviesTable;
    // End of variables declaration//GEN-END:variables
}
